services:


  db:
    image: docker.arvancloud.ir/postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - catalog
    restart: always

  web:
    build: .
    command: sh -c "mkdir -p /app/static && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_data:/app/staticfiles
      - static_raw_data:/app/static
      - media_data:/app/media
    networks:
      - catalog
    restart: always

volumes:
  postgres_data:
  static_data:
  static_raw_data:
  media_data:

networks:
  catalog: